name: York's Lab
description: Thinking, Blogging and Sharing
meta_description: "York's Lab"

# markdown: redcarpet
# extension: tables
kramdown:
  input: GFM
#pygments: true
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'York'
# destination: /Users/yty/Develop/York921

